[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist" # or your frontend output

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
