[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  included_files = [
    "node_modules/lightningcss/**",
    "node_modules/lightningcss/pkg/**/*",
    "node_modules/lightningcss/node/**/*"
]
